#!/usr/bin/python2
# PURPOSE: To export address data stored in a .xlsx file into a .docx file that 
# is pre-formatted for making printable labels. 
# Assumes that the addresses in the .xls file are organized under the following headings: 
#
#   COLUMN A				COLUMN B		COLUMN C		COLUMN D	COLUMN E	 COLUMN F			
#   PRINCIPAL NAME OF HOUSEHOLD / PRINCIPAL ADDRESSEE(S) / OTHER HOUSEHOLD MEMBERS / ADDRESS LINE 1 / ADDRESS LINE 2 / ADDRESS LINE 3 ...
#
# Assumes that the output file is pre-formatted for label-making, with the data to be organized in a .docx table. 
# USAGE: ./addresses_export_v1 Addresses.xlsx

import sys
import docx
import xlrd



# Give the location of the input file 
loc = (sys.argv[1]) 
  
# To open Workbook 
wb = xlrd.open_workbook(loc)

# Input the sheet index of the input worksheet. Default is 0.
sheet = wb.sheet_by_index(0)
  
# Open the label-making .docx to be written
doc = docx.Document('Alphabetized_Addresses.docx')

# Assumes there is a header and that the first col contains principal last name; so we start by reading row 1, column 1 
for n in range(1, sheet.nrows):
	# The contents of the nth row of the input file fill the cell with coordinates ((n-1)/3, 2*((n-1) % 3)
	M = (n-1)/3
	P = 2*((n-1) % 3)

	if M == len(doc.tables[0].rows):
		doc.tables[0].add_row()
	cell = doc.tables[0].rows[M].cells[P]
	cell.text = ''
	cell.paragraphs[0].text = sheet.cell_value(n, 1)
	if sheet.cell_value(n, 2) == '':
		cell.add_paragraph(sheet.cell_value(n, 3))
		cell.add_paragraph(sheet.cell_value(n, 4))
		if sheet.cell_value(n, 5) != '': 
			cell.add_paragraph(sheet.cell_value(n, 5))
	else: 
		cell.add_paragraph(sheet.cell_value(n, 2))
		cell.add_paragraph(sheet.cell_value(n, 3))
		if sheet.cell_value(n, 4) != '': 
			cell.add_paragraph(sheet.cell_value(n, 4))
			if sheet.cell_value(n, 5) != '': 
				cell.add_paragraph(sheet.cell_value(n, 5))

	# Print success message for testing:
	# print('No problems exporting row ' + str(n) + ' of input file.')

# Polish the document so it looks pretty:
# Set text alignment in each cell to CENTER
#from docx.enum.text import WD_ALIGN_PARAGRAPH
#doc.tables[0].style.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.CENTER

# Set font to Times New Roman and Size to 10pt.
#doc.tables[0].style.font.size = 10
#doc.tables[0].style.font.name = 'Times New Roman'

doc.save('Alphabetized_Addresses.docx')
